// Project: FPC 3.2.2 Referenz Handbuch
// Generated by HelpNDoc - https://www.helpndoc.com

unit FreePascal;

interface

const
  // Format: HELP_help-id = help-context
  HELP_Lizenz-Bittelesen = 2; 				 // Topic: "Lizenz - Bitte lesen !!!"
  HELP_Uberblick = 0; 				 // Topic: "Überblick"
  HELP_GNUDokumentation = 291; 				 // Topic: "GNU Dokumentation"
  HELP_GNU-Manifest = 289; 				 // Topic: "GNU - Manifest"
  HELP_FSundOSS = 290; 				 // Topic: "FS und OSS"
  HELP_Lizenzen-GPL = 280; 				 // Topic: "Lizenzen - GPL"
  HELP_Version3 = 292; 				 // Topic: "Version 3"
  HELP_Deutsch1 = 281; 				 // Topic: "Deutsch"
  HELP_Englisch1 = 282; 				 // Topic: "Englisch"
  HELP_Version2 = 293; 				 // Topic: "Version 2"
  HELP_Deutsch3 = 286; 				 // Topic: "Deutsch"
  HELP_Englisch2 = 287; 				 // Topic: "Englisch"
  HELP_Lizenzen-LGPL = 283; 				 // Topic: "Lizenzen - LGPL"
  HELP_FAQ-Questions-Answers = 303; 				 // Topic: "FAQ - Questions-Answers"
  HELP_1-BasicQuestions = 305; 				 // Topic: "1 - Basic Questions"
  HELP_2-Generalunderstanding = 306; 				 // Topic: "2 - General understanding"
  HELP_3-UsingGNULicenses = 307; 				 // Topic: "3 - Using GNU License's"
  HELP_4-Distribution = 308; 				 // Topic: "4 - Distribution"
  HELP_5-UsingPrograms = 309; 				 // Topic: "5 - Using Program's"
  HELP_6-CombiningWorkCode = 310; 				 // Topic: "6 - Combining Work+Code"
  HELP_7-Violation = 311; 				 // Topic: "7 - Violation"
  HELP_Version4 = 285; 				 // Topic: "Version 3"
  HELP_Deutsch2 = 284; 				 // Topic: "Deutsch"
  HELP_Englisch3 = 295; 				 // Topic: "Englisch"
  HELP_1PascalZeichenundSymbole = 11; 				 // Topic: "1.  Pascal Zeichen und Symbole"
  HELP_2Konstanten = 23; 				 // Topic: "2.  Konstanten"
  HELP_3Typen = 27; 				 // Topic: "3.  Typen"
  HELP_4Variablen = 75; 				 // Topic: "4.  Variablen"
  HELP_5Objekte = 83; 				 // Topic: "5.  Objekte"
  HELP_6Klassen = 97; 				 // Topic: "6.  Klassen"
  HELP_7SchnittstellenInterfaces = 124; 				 // Topic: "7.  Schnittstellen (Interface's)"
  HELP_8Generics = 133; 				 // Topic: "8.  Generics"
  HELP_9ErweiterteRecords = 147; 				 // Topic: "9.  Erweiterte Record's"
  HELP_10KlassenRecordsundTypen-Helfer = 151; 				 // Topic: "10.  Klassen, Record's, und Typen-Helfer"
  HELP_11ObjektorientiertePascal-Klasse = 159; 				 // Topic: "11.  Objektorientierte Pascal - Klassen"
  HELP_12Ausdrucke = 170; 				 // Topic: "12.  Ausdrücke"
  HELP_13Anweisungen = 187; 				 // Topic: "13.  Anweisungen"
  HELP_14BenutzungvonFunktionenundProze = 203; 				 // Topic: "14.  Benutzung von Funktionen und Prozeduren"
  HELP_15OperatorenUberladung = 249; 				 // Topic: "15.  Operatoren Überladung"
  HELP_16ProgrammeModuleundBlocke = 259; 				 // Topic: "16.  Programme, Module und Blöcke"
  HELP_17Ausnahmen = 271; 				 // Topic: "17.  Ausnahmen"
  HELP_18Assembler = 274; 				 // Topic: "18.  Assembler"
  HELP_181Anweisungen = 275; 				 // Topic: "18.1.  Anweisungen"
  HELP_182ProzedurenundFunktionen = 276; 				 // Topic: "18.2.  Prozeduren und Funktionen"

implementation

end.
