# Project: Einfache Lehrn-Hilfen
# Generated by HelpNDoc - https://www.helpndoc.com

from enum import Enum

class Help_FreePascal(Enum):
    Vorlage = 4
    VorlageHeader = 5
    Lizenz-Bittelesen = 2
    Inhalt = 3
    ListederTabellen = 6
    UberdiesesHandbuch = 7
    Bezeichnungen = 8
    SyntaxDiagramme = 9
    UberdieSprachePascal = 10
    1PascalZeichenundSymbole = 11
    2Konstanten = 23
    3Typen = 27
    4Variablen = 75
    5Objekte = 83
    6Klassen = 97
    7SchnittstellenInterfaces = 124
    8Generics = 133
    9ErweiterteRecords = 147
    10KlassenRecordsundTypen-Helfer = 151
    11ObjektorientiertePascal-Klasse = 159
    12Ausdrucke = 170
    13Anweisungen = 187
    14BenutzungvonFunktionenundProze = 203
    15OperatorenUberladung = 249
    16ProgrammeModuleundBlocke = 259
    17Ausnahmen = 271
    18Assembler = 274
    181Anweisungen = 275
    182ProzedurenundFunktionen = 276
