/* Project: FPC 3.2.2 Referenz Handbuch */
/* Generated by HelpNDoc - https://www.helpndoc.com */

#ifndef __FreePascal.def_HEADER__
#define __FreePascal.def_HEADER__

#define HELP_Lizenz-Bittelesen 2
#define HELP_Uberblick 0
#define HELP_GNUDokumentation 291
#define HELP_GNU-Manifest 289
#define HELP_FSundOSS 290
#define HELP_Lizenzen-GPL 280
#define HELP_Version3 292
#define HELP_Deutsch1 281
#define HELP_Englisch1 282
#define HELP_Version2 293
#define HELP_Deutsch3 286
#define HELP_Englisch2 287
#define HELP_Lizenzen-LGPL 283
#define HELP_FAQ-Questions-Answers 303
#define HELP_1-BasicQuestions 305
#define HELP_2-Generalunderstanding 306
#define HELP_3-UsingGNULicenses 307
#define HELP_4-Distribution 308
#define HELP_5-UsingPrograms 309
#define HELP_6-CombiningWorkCode 310
#define HELP_7-Violation 311
#define HELP_Version4 285
#define HELP_Deutsch2 284
#define HELP_Englisch3 295
#define HELP_1PascalZeichenundSymbole 11
#define HELP_2Konstanten 23
#define HELP_3Typen 27
#define HELP_4Variablen 75
#define HELP_5Objekte 83
#define HELP_6Klassen 97
#define HELP_7SchnittstellenInterfaces 124
#define HELP_8Generics 133
#define HELP_9ErweiterteRecords 147
#define HELP_10KlassenRecordsundTypen-Helfer 151
#define HELP_11ObjektorientiertePascal-Klasse 159
#define HELP_12Ausdrucke 170
#define HELP_13Anweisungen 187
#define HELP_14BenutzungvonFunktionenundProze 203
#define HELP_15OperatorenUberladung 249
#define HELP_16ProgrammeModuleundBlocke 259
#define HELP_17Ausnahmen 271
#define HELP_18Assembler 274
#define HELP_181Anweisungen 275
#define HELP_182ProzedurenundFunktionen 276

#endif
