/* Project: Einfache Lehrn-Hilfen */
/* Generated by HelpNDoc - https://www.helpndoc.com */

#ifndef __FreePascal.def_HEADER__
#define __FreePascal.def_HEADER__

#define HELP_Vorlage 4
#define HELP_VorlageHeader 5
#define HELP_Lizenz-Bittelesen 2
#define HELP_Inhalt 3
#define HELP_ListederTabellen 6
#define HELP_UberdiesesHandbuch 7
#define HELP_Bezeichnungen 8
#define HELP_SyntaxDiagramme 9
#define HELP_UberdieSprachePascal 10
#define HELP_1PascalZeichenundSymbole 11
#define HELP_2Konstanten 23
#define HELP_3Typen 27
#define HELP_4Variablen 75
#define HELP_5Objekte 83
#define HELP_6Klassen 97
#define HELP_7SchnittstellenInterfaces 124
#define HELP_8Generics 133
#define HELP_9ErweiterteRecords 147
#define HELP_10KlassenRecordsundTypen-Helfer 151
#define HELP_11ObjektorientiertePascal-Klasse 159
#define HELP_12Ausdrucke 170
#define HELP_13Anweisungen 187
#define HELP_14BenutzungvonFunktionenundProze 203
#define HELP_15OperatorenUberladung 249
#define HELP_16ProgrammeModuleundBlocke 259
#define HELP_17Ausnahmen 271
#define HELP_18Assembler 274
#define HELP_181Anweisungen 275
#define HELP_182ProzedurenundFunktionen 276

#endif
